---
title: "SVM Model for Predicting Soccer Match Winners"
author: "Ismayil, Vadym, Ivan"
date: "`r Sys.Date()`"
output: html_document
---



```{r}
install.packages("e1071")
library(e1071)
library(caret)
library(dplyr)
library(tidyverse)
library(ggplot2)
```


```{r}
# Load Data
matches_1930_2022 <- read.csv("matches_1930_2022.csv")
```


```{r}
world_cup <- read.csv("C:/Users/Vadym/Desktop/Reproducible/project/world_cup.csv")
```


```{r}
# Data Preparation
matches <- matches_1930_2022[, -c(9, 10, 11, 12, 14,15,18,19,20,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45)]
```


```{r}
replace_teams <- function(matches) {
  matches$home_team[matches$home_team %in% c("German DR", "Germany FR")] <- "Germany"
  matches$home_team[matches$home_team == "Soviet Union"] <- "Russia"
  
  matches$away_team[matches$away_team %in% c("German DR", "Germany FR")] <- "Germany"
  matches$away_team[matches$away_team == "Soviet Union"] <- "Russia"
  
  return(matches)
}

#### Activate function replace_teams
matches <- replace_teams(matches)
```


```{r}
team_name <- list()
index <- 0

for (i in 1:nrow(matches)) {
  name <- matches[i, "home_team"]
  if (!(name %in% names(team_name))) {
    team_name[[name]] <- index
    index <- index + 1
  }
  
  name <- matches[i, "away_team"]
  if (!(name %in% names(team_name))) {
    team_name[[name]] <- index
    index <- index + 1
  }
}

team_name
```



```{r}
championships <- table(ifelse(world_cup$Champion == "West Germany", "Germany", world_cup$Champion))
championships
```



```{r}
# Create a countplot
ggplot(world_cup, aes(x = Champion)) +
  geom_bar(fill = "steelblue") +
  labs(x = "Country", y = "Number of World Cup Championships") +
  ggtitle("Number of World Cup Championships by Country") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```




```{r}
matches$Home_Team_Champions <- 0
matches$Away_Team_Champions <- 0


if (!is.null(championships[matches$home_team])) {
  matches$Home_Team_Champions <- championships[matches$home_team]
}

if (!is.null(championships[matches$away_team])) {
  matches$Away_Team_Champions <- championships[matches$away_team]
}

```


```{r}
matches$Winner <- "-"

calculate_winner <- function(matches) {
  home_team_goal <- as.integer(matches$home_score)
  away_team_goal <- as.integer(matches$away_score)
  matches$Winner <- ifelse(home_team_goal == away_team_goal, 0, ifelse(home_team_goal > away_team_goal, 1, 2))
  
  return(matches)
}

matches <- calculate_winner(matches)

table(matches$Winner)
```


```{r}
replace_team_name <- function(matches) {
  matches$home_team <- team_name[matches$home_team]
  matches$away_team <- team_name[matches$away_team]
  return(matches)
}

matches <- replace_team_name(matches)
```


```{r}
matches <- matches[, -c(5, 8, 9, 10, 11, 12, 13)]
matches <- matches[, -c(3,4,5,6)]


matches$Away_Team_Champions <- ifelse(is.na(matches$Away_Team_Champions), 0, matches$Away_Team_Champions)
matches$Home_Team_Champions <- ifelse(is.na(matches$Home_Team_Champions), 0, matches$Home_Team_Champions)

```

```{r}
# Unlist the dataset
class(matches)

matches$Home_Team_Champions<-as.numeric(matches$Home_Team_Champions)
matches$Away_Team_Champions<-as.numeric(matches$Away_Team_Champions)
matches$away_team <- unlist(matches$away_team)
matches$home_team <- unlist(matches$home_team)

#mean_value <- mean(matches$home_xg, na.rm = TRUE)
#matches$home_xg <- ifelse(is.na(matches$home_xg), mean_value, matches$home_xg)
#mean_value1 <- mean(matches$away_xg, na.rm = TRUE)
#matches$away_xg <- ifelse(is.na(matches$away_xg), mean_value1, matches$away_xg)
```

```{r}
# Create indices for the training and test sets
sample <- sample(c(TRUE, FALSE), nrow(matches), replace=TRUE, prob=c(0.7,0.3))
train <- matches[sample, ]
test <- matches[!sample, ]  
```

```{r}
####modeling 

model <- svm(Winner ~.,
                 data = train,
                 type = 'C-classification',
                 kernel = 'linear',
                scale = FALSE)
model
```



```{r}
pred_test <- predict(model,newdata = test)
pred_test
```

```{r}
pred_train1 <- predict(model, train)
mean(pred_train1 == train$Winner)
```


```{r}
####evaluation
pred_test <- predict(model, test)
mean(pred_test == test$Winner)
```


```{r}
# Create a data frame with the true and predicted labels
results <- data.frame(Actual = test$Winner, Predicted = pred_test)
```


```{r}
# Use the caret package's confusionMatrix() function to calculate evaluation metrics
cm <- confusionMatrix(data = factor(results$Predicted),
                      reference = factor(results$Actual))
# Print the classification report
print(cm)
```

